language: java
dist: trusty
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java9-installer

before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.zip
  - unzip -qq apache-maven-3.5.0-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.5.0
  - export PATH=$M2_HOME/bin:$PATH
  - echo "MAVEN_OPTS='-Dmaven.repo.local=$HOME/.m2/repository -Xmx1g -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss:SSS'" > ~/.mavenrc
  - wget https://github-production-release-asset-2e65be.s3.amazonaws.com/66405340/8ba46300-54b9-11e9-971e-2fdce4ef2a0d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20190726%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190726T140126Z&X-Amz-Expires=300&X-Amz-Signature=3d2945d544e7c54bc4a8776bd5d6031e503ecd0107b2d9be7b9df40c48ac26ef&X-Amz-SignedHeaders=host&actor_id=45619648&response-content-disposition=attachment%3B%20filename%3Dinterpreter.jar&response-content-type=application%2Foctet-stream -O /home/travis/build/prolobjectlink/prolobjectlink-jpi-jeckpro/interpreter.jar
  - mvn install:install-file -Dfile=interpreter.jar -DgroupId=com.xlog -DartifactId=interpreter -Dversion=1.3.6 -Dpackaging=jar

install:
  -

matrix:
   fast_finish: true
   include:
   -  jdk: oraclejdk8
      env:
      - DESC="Install Java 8"
      - CMD="mvn clean install site"
   -  jdk: oraclejdk9
      env:
      - DESC="Install Java 9"
      - CMD="mvn clean install site"
      
after_success:
  - echo "<settings><servers><server><id>ossrh</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server></servers></settings>" > ~/settings.xml
  - mvn deploy --settings ~/settings.xml
      
script: eval travis_wait 35 $CMD

cache:
  directories:
  - ~/.m2
